export const ESTADOS_CIUDADES: Record<string, string[]> = {
  "Aguascalientes": ["Aguascalientes", "Jesús María", "Calvillo", "Pabellón de Arteaga"],
  "Baja California": ["Tijuana", "Mexicali", "Ensenada", "Tecate", "Playas de Rosarito"],
  "Baja California Sur": ["La Paz", "Los Cabos", "Loreto", "Mulegé", "Comondú"],
  "Campeche": ["Campeche", "Ciudad del Carmen", "Champotón", "Calkiní"],
  "Chiapas": ["Tuxtla Gutiérrez", "San Cristóbal de las Casas", "Tapachula", "Comitán", "Palenque"],
  "Chihuahua": ["Chihuahua", "Ciudad Juárez", "Delicias", "Cuauhtémoc", "Parral"],
  "Ciudad de México": ["Álvaro Obregón", "Azcapotzalco", "Benito Juárez", "Coyoacán", "Cuajimalpa", "Cuauhtémoc", "Gustavo A. Madero", "Iztacalco", "Iztapalapa", "Magdalena Contreras", "Miguel Hidalgo", "Milpa Alta", "Tláhuac", "Tlalpan", "Venustiano Carranza", "Xochimilco"],
  "Coahuila": ["Saltillo", "Torreón", "Monclova", "Piedras Negras", "Acuña"],
  "Colima": ["Colima", "Manzanillo", "Tecomán", "Villa de Álvarez", "Armería"],
  "Durango": ["Durango", "Gómez Palacio", "Lerdo", "Santiago Papasquiaro"],
  "Guanajuato": ["León", "Guanajuato", "Irapuato", "Celaya", "Salamanca", "San Miguel de Allende"],
  "Guerrero": ["Acapulco", "Chilpancingo", "Zihuatanejo", "Taxco", "Iguala"],
  "Hidalgo": ["Pachuca", "Tulancingo", "Tula de Allende", "Actopan", "Huejutla"],
  "Jalisco": ["Guadalajara", "Zapopan", "San Pedro Tlaquepaque", "Tonalá", "Puerto Vallarta", "Lagos de Moreno"],
  "México": ["Toluca", "Ecatepec", "Naucalpan", "Tlalnepantla", "Nezahualcóyotl", "Metepec", "Texcoco"],
  "Michoacán": ["Morelia", "Uruapan", "Zamora", "Lázaro Cárdenas", "Apatzingán"],
  "Morelos": ["Cuernavaca", "Jiutepec", "Cuautla", "Temixco", "Yautepec"],
  "Nayarit": ["Tepic", "Bahía de Banderas", "Santiago Ixcuintla", "Compostela"],
  "Nuevo León": ["Monterrey", "Guadalupe", "San Nicolás de los Garza", "Apodaca", "Santa Catarina", "San Pedro Garza García"],
  "Oaxaca": ["Oaxaca de Juárez", "Salina Cruz", "Juchitán", "Tuxtepec", "Huatulco"],
  "Puebla": ["Puebla", "Tehuacán", "San Martín Texmelucan", "Atlixco", "Cholula"],
  "Querétaro": ["Querétaro", "San Juan del Río", "El Marqués", "Corregidora"],
  "Quintana Roo": ["Cancún", "Chetumal", "Playa del Carmen", "Cozumel", "Tulum"],
  "San Luis Potosí": ["San Luis Potosí", "Soledad de Graciano Sánchez", "Matehuala", "Rioverde"],
  "Sinaloa": ["Culiacán", "Mazatlán", "Los Mochis", "Guasave", "Navolato"],
  "Sonora": ["Hermosillo", "Ciudad Obregón", "Nogales", "San Luis Río Colorado", "Guaymas"],
  "Tabasco": ["Villahermosa", "Cárdenas", "Macuspana", "Comalcalco", "Paraíso"],
  "Tamaulipas": ["Reynosa", "Matamoros", "Nuevo Laredo", "Tampico", "Victoria"],
  "Tlaxcala": ["Tlaxcala", "Apizaco", "Huamantla", "Chiautempan"],
  "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos", "Córdoba", "Orizaba", "Poza Rica"],
  "Yucatán": ["Mérida", "Valladolid", "Progreso", "Umán", "Tizimín"],
  "Zacatecas": ["Zacatecas", "Guadalupe", "Fresnillo", "Jerez", "Río Grande"],
};

export const ESTADOS = Object.keys(ESTADOS_CIUDADES).sort();
